# configuration for Eureka client shared by application microservices (spring cloud discovery).
# This allows local microservices to register with service-registry as local clients
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
